import Database from 'better-sqlite3';
import { mkdir, rm } from 'node:fs/promises';
import { dirname } from 'node:path';
import type { PGlite } from '@electric-sql/pglite';

type SchemaObject = { name: string; sql: string };
type LegacyTable = SchemaObject & { columns: string[] };

export async function importSqliteBranch(sourceFile: string, targetDir: string) {
  const legacy = new Database(sourceFile, { readonly: true });
  const { PGlite } = await import('@electric-sql/pglite');
  await rm(targetDir, { recursive: true, force: true });
  await mkdir(dirname(targetDir), { recursive: true });
  const postgres = await PGlite.create(targetDir);
  try {
    const tables = legacy.prepare(`
      SELECT name, sql FROM sqlite_master
      WHERE type = 'table' AND name NOT LIKE 'sqlite_%' AND sql IS NOT NULL
      ORDER BY name
    `).all() as SchemaObject[];
    const imported: LegacyTable[] = [];
    for (const table of tables) {
      await postgres.query(translateSqliteSchema(table.sql));
      const columns = legacy.prepare(`PRAGMA table_info(${quoteIdentifier(table.name)})`).all() as { name: string }[];
      imported.push({ ...table, columns: columns.map((column) => column.name) });
    }
    await copyRows(legacy, postgres, imported);
    await copyIndexes(legacy, postgres);
    await copyViews(legacy, postgres);
    return postgres;
  } catch (error) {
    await postgres.close();
    await rm(targetDir, { recursive: true, force: true });
    throw new Error(`Could not migrate SQLite branch data: ${error instanceof Error ? error.message : error}`);
  } finally {
    legacy.close();
  }
}

function translateSqliteSchema(sql: string) {
  return sql
    .replace(/\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b/gi, 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
    .replace(/\bINTEGER\s+PRIMARY\s+KEY\b/gi, 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
    .replace(/\bDATETIME\b/gi, 'TIMESTAMP')
    .replace(/\bBLOB\b/gi, 'BYTEA')
    .replace(/\bUNSIGNED\b/gi, '')
    .replace(/\s+COLLATE\s+NOCASE\b/gi, '')
    .replace(/\s+WITHOUT\s+ROWID\b/gi, '')
    .replace(/\s+STRICT\s*$/i, '');
}

async function copyRows(legacy: Database.Database, postgres: PGlite, tables: LegacyTable[]) {
  for (const table of tables) {
    const rows = legacy.prepare(`SELECT * FROM ${quoteIdentifier(table.name)}`).all() as Record<string, unknown>[];
    if (!rows.length || !table.columns.length) continue;
    const columns = table.columns.map(quoteIdentifier).join(', ');
    const markers = table.columns.map((_, index) => `$${index + 1}`).join(', ');
    const insert = `INSERT INTO ${quoteIdentifier(table.name)} (${columns}) VALUES (${markers})`;
    for (const row of rows) await postgres.query(insert, table.columns.map((column) => row[column]));
    await reseedIdentity(postgres, table);
  }
}

async function reseedIdentity(postgres: PGlite, table: LegacyTable) {
  const id = /(?:^|[,\s(])("?[\w]+"?)\s+INTEGER\s+PRIMARY\s+KEY(?:\s+AUTOINCREMENT)?\b/i.exec(table.sql)?.[1];
  if (!id) return;
  const column = id.replaceAll('"', '');
  await postgres.query(`SELECT setval(pg_get_serial_sequence(${quoteLiteral(table.name)}, ${quoteLiteral(column)}), COALESCE(MAX(${quoteIdentifier(column)}), 1), MAX(${quoteIdentifier(column)}) IS NOT NULL) FROM ${quoteIdentifier(table.name)}`);
}

async function copyIndexes(legacy: Database.Database, postgres: PGlite) {
  const indexes = legacy.prepare("SELECT sql FROM sqlite_master WHERE type = 'index' AND sql IS NOT NULL ORDER BY name").all() as { sql: string }[];
  for (const index of indexes) await postgres.query(translateSqliteSchema(index.sql));
}

async function copyViews(legacy: Database.Database, postgres: PGlite) {
  const views = legacy.prepare("SELECT sql FROM sqlite_master WHERE type = 'view' AND sql IS NOT NULL ORDER BY name").all() as { sql: string }[];
  for (const view of views) await postgres.query(translateSqliteSchema(view.sql));
}

function quoteIdentifier(value: string) {
  return `"${value.replaceAll('"', '""')}"`;
}

function quoteLiteral(value: string) {
  return `'${value.replaceAll("'", "''")}'`;
}
